# golang-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facturacion-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facturacion-front
  template:
    metadata:
      labels:
        app: facturacion-front
    spec:
      containers:
      - name: facturacion-front
        image: gcr.io/annular-form-401215/gcr-alpine:{GITHUB_SHA}
        ports:
        - containerPort: 3050
